import React from "react";

import Layout from "../components/layout";
import SEO from "../components/seo";
import titleSVG from "../images/otsikko.svg";
class IndexPage extends React.Component {
  render() {
    return (
      <Layout>
        <SEO title="Exhibition" />
        <div className="canvas" ref={this.myRef}></div>
        <div className="canvas2"></div>
        <div
          style={{
            display: `flow-root`,
            fontFamily: `Portland-Bold`,
            textTransform: `uppercase`
          }}
        >
          <div
            className={`wave`}
            style={{ float: `right`, letterSpacing: `0.05em` }}
          >
            <p style={{ marginBottom: `0.1rem` }}>Lapinlahti Hospital Area</p>
            <p>10-26 April</p>
          </div>
        </div>
        <p
          style={{
            marginTop: `2rem`,
            marginBottom: `3rem`,
            textTransform: `uppercase`,
            letterSpacing: `0.1em`
          }}
        >
          Aalto Media Lab Spring Exhibition
        </p>
        <h1 style={{ display: `none` }}>Ristiaallokko</h1>
        <div style={{ maxWidth: `500px`, marginBottom: `2rem` }}>
          <img src={titleSVG} alt="Ristiaallokko" />
        </div>
        <div style={{ maxWidth: `40rem`, margin: `auto` }}>
          <p>
            Cross Waves is a sea state that occurs when two or more nonparallel wave systems meet. The waves generated by this phenomenon are dangerous to swimmers, boats, and ships caught between the crossing waves.
          </p>
          <p>
            Cross Waves is also the name of the Spring exhibition of Aalto Media Lab students. It is an exhibition that highlights 13 new interactive artworks that have been created in the meeting point of art and technology. The exhibition is divided into two locations within the former Lapinlahti Psychiatric Hospital area: Mental Museum Pop-Up Gallery and the Venetsia building.
          </p>
          <p>
            Ristiaallokko | Cross Waves exhibition is the outcome of the Interactive Art course taught by Matti Niinimäki in Aalto University. The aim of the course is to explore the notion of interaction within the context of new media art.
          </p>
          <h2>Where</h2>
          <p>
            <a rel="noopener noreferrer" target="_blank" href="https://www.google.com/maps/place/Lapinlahden+sairaala/@60.1676198,24.9128495,15z/data=!4m5!3m4!1s0x0:0xb82cd21f9c6bb53b!8m2!3d60.1676198!4d24.9128495">Lapinlahdenpolku 1, Helsinki</a>
          </p>
        </div>
      </Layout>
    );
  }
}

export default IndexPage;
